### ISSUE TITLE
Implement theme song system in portal.

### ISSUE THREAD

**Issue by jabelone** [HSBNE/hsbneportal#39]

**Comment by sjlongland** [comment]
Just thinking… would this be stored in the SQL database and just dumped out to the spool directory on demand, or would you store the files on-disk?

I'm thinking something along the lines of:
```
import subprocess

# …

def filetosln(input_blob, in_format='mp3'):
    """
    Convert an MP3 (given as a bytestring) to a SLN (returned as a bytestring)
    """
    popen = subprocess.Popen(
        ['/usr/bin/sox', '-t', in_format, '-', '-r', '8000', '-c', '1', '-s', '-w', '-t', 'sln', '-'],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    (sln_data, _) = popen.communicate(stdin=input_blob)
    return sln_data
```

You'd probably store both formats so you've got something that's playable… it might be feasible to combine this with [python-magic](https://github.com/ahupp/python-magic) to auto-detect whether it's an MP3, Ogg/Vorbis or whatever.

**Comment by blip2** [comment]
Sound defo be using python-sox rather than subprocess
I would probably use a FileField to store a local mp3 with django
I assume we want to bypass the php and use asterisk-python to talk directly to the phone system?
I can prototype something but it'll need tested in-situ...

**Comment by jabelone** [comment]
Sorry @sjlongland didn't see your reply.

@blip2 that sounds like a good idea. It's not super important but if you get a chance to poke at it while at the space next time ping @nogthree and he can probably get you access to the asterisk side of things.

**Comment by sjlongland** [comment]
@blip2 Well, to each their own, I did look at `python-sox` but wasn't sure whether we wanted to bring in another dependency or not for something as trivial as piping some raw audio data through a command.

I'll admit I haven't tested the above code. :-)

For sure, using a library ought to make the code more readable/understandable by abstracting the details of the piping and `sox` call.

@jabelone No biggie.  Little emails like the ones Github generate can get easily lost in the noise.

**Comment by nog3** [comment]
So bumping this, because we've shuffled the infrastructure around a bit.

Current plan is to run FreePBX (or even just asterisk) in a docker container on the portal host. The docker container will expose local volumes for asterisk's spool folder, the custom sounds folder and the asterisk config folder so the container is stateless.

The portal will interact with these two volumes in two ways:

1. /var/asterisk/spool (/var/spool/asterisk/outgoing inside the container) is where a spool file will need to be created to make the call to the intercom extension for theme playback. 
 * The filename for this must end with .call on the format, currently this is generated as theme_nickname.call
 * Format for this is as standard asterisk spool format, which is as follows:
`Channel: $extnumber \n" );
RetryTime: 15\n
MaxRetries: 5\n
Application: Playback\n
Data: $filename\n`

2. /var/asterisk/custom (/var/lib/asterisk/sounds/en/ inside the container) is where the portal will need to place the theme files for playback, after running them through sox to turn them into an SLN file with the right encoding.
*  Sox format is 
`sox $target_dir/theme_$nick.mp3 -t raw -r 8000  -c 1 $sound_dir/theme_$nick.sln trim 0 15`

Now aside from all of this, we will need to add a flag to the door model to allow for toggling whether or not it causes themes to be played and maybe some rate limiting to make it not happen unless you swipe x hours apart.

**Comment by jabelone** [comment]
This is mainly for my future reference. To trigger the existing system to play a theme song, you should make a GET request to this endpoint like so:

`https://10.0.1.50/playmp3.php?nickname=jabelone`

To support uploads I think it would probably be best to just upload the file through the portal than SCP it across to the phone system box. That is the simplest way of getting it to work for now.
