### ISSUE TITLE
Refresh the member list modal after saving details

### ISSUE THREAD

**Issue by jabelone** [HSBNE/hsbneportal#52]
Currently, the member list modal in the admin section doesn't refresh when you click "Make Member" or "Resend to Xero" and this is a little confusing. When these buttons are used, when the server replies we should refresh the modal's content.

**Comment by dnafication** [comment]
http://127.0.0.1:8000/members/list/#

Are you talking about below? Is this issue closed?
![image](https://user-images.githubusercontent.com/6381587/46783308-7ace2c80-cd75-11e8-89bf-3bde43006be0.png)

**Comment by dnafication** [comment]
Oops, its not. I will try to figure it out. Cheers.

**Comment by jabelone** [comment]
Nope it's still open :)
Basically you'll just need to find the JavaScript that runs to inject the different sections of the modal and re-run that after you click the make member, resend to xero or save buttons.

**Comment by dnafication** [comment]
Roger that :+1:  thanks for the tip. Will dig into js now. Exciting!

**Comment by dnafication** [comment]
May be we'll need to reload the list page as well after closing the modal? I observed that even the data table isn't getting updated with the new data until refreshed... or that should be for another issue? ;)

**Comment by dnafication** [comment]
Morning @jabelone, seems like modal is initialized by data which gets injected when the django template is rendered. On saving the modal form, it only updates the form with form data and none of other elements of the modal. 
Also, the `h5` with id `admin-member-modal-name` gets a pre formed html content during initialization, we may need to pass in separate data for first name, last name and xero status so that we can handle it in js. What do you think?
