### ISSUE TITLE
Database and Log file locations hardcoded in latest merge

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#93]
In the latest merge for settings.py (https://github.com/HSBNE/hsbneportal/commit/f5066fcb08fb91bb35fac2d6f50d9169d5f37fa3#diff-5f8d3c110ee5f8561e31464c174b5e39) the Database and Log file locations have been hardcoded to /usr/src/data/db.sqlite3 and /usr/src/logs/django.log respectively.

This breaks development for anyone working in Mac OSX Catalina or above, since these file paths are within the readonly file system of APFS. Can we please either use ENV vars or not hardcode?

**Comment by jabelone** [comment]
Let me have a think about this. The reason they're hardcoded is because now we have docker support, the idea is that the codebase should always run in the docker container. From experience, this obviously isn't the most ideal way to develop stuff as the built in django development server is ideal for that. I think having an optional environment variable that specifies an alternate location is probably a good solution.

**Comment by jabelone** [comment]
This has been fixed with the option to specify an environment variable to a custom location.
